name: Mingkai Jiang
description: Academic website
menu:
 - page: News
   url: /news
 - page: Publication
   url: /publication
   links:
    - title: Spotlight
      url: "#spotlight-papers"
    - title: Full publication
      url: "#full-pub-list"
 - page: Research Projects
   url: /research
   links:
    - title: "Project One"
      url: "#project-one"
    - title: "Project Two"
      url: "#project-two"
    - title: "Project Three"
      url: "#project-three"
    - title: "Project Four"
      url: "#project-four"
 - page: Curriculum Vitae
   url: /cv
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
    - title: Positions
      url: "#positions"
    - title: Miscellaneous
      url: "#miscellaneous"
 - page: Teaching
   url: /teaching
 - page: Media
   url: /media
 - page: Resources
   url: /resources
   links:
    - title: Datasets
      url: "#datasets"
    - title: Useful links
      url: "#links"
menu_external:
 - title: Twitter
   url: "https://twitter.com/jiangmingkai"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: mingkaijiang.github.io
locale: en_GB

theme: jekyll-theme-midnight